### ISSUE TITLE
Clion: Could not find package configuration file provided by "sb_utils"

### ISSUE THREAD

**Issue by garethellis0** [UBC-Snowbots/Snowflake#116] opened 2017-03-03 05:53 UTC
- Basically, sb_utils is not being built before a package that requires it (most packages do), and so the packages fail to compile.
- Not sure why this is
- Should be able to reproduce by running `git clean` in `IGVC-2017` and then trying to run clion and build a node from a package that depends on `sb_utils` like `vision_decision` from the `decision` package
- can be fixed by running `catkin build sb_utils` from `IGVC-2017`, (or `catkin_make sb_utils`), `source devel/setup.bash`, and re-open clion from the same terminal. things should compile now
- Produces an error like this:
![image](https://cloud.githubusercontent.com/assets/9075711/23539764/411e3398-ff92-11e6-8654-ae0fa0dac402.png)

**Comment by ValRat** [comment] 2017-10-14 18:13
Seems good and we can't reproduce. Closing this.

**Closed by ValRat** 2017-10-14 18:13 UTC
Labels: bug, CMake
