### ISSUE TITLE
Create a ROS Abstraction for Radio Communications

### ISSUE THREAD

**Issue by RobynCastro** [UBC-Snowbots/Snowflake#343] opened 2018-09-08 17:28 UTC
We need to be able to connect to the robot like it's another computer.

**Comment by garethellis0** [comment] 2018-09-08 17:34
In general, if you have two computers running on the same network, it's fairly trivial to run ROS nodes on both computers (see: http://wiki.ros.org/ROS/Tutorials/MultipleMachines). The real challenge here is being able to have multiple computers on the same network over a radio link. We could potentially use something like: https://www.avalan.com/products/900mhz/aw900xtr-outdoor-wireless-ethernet-radio/, but it might be expensive, and we have to keep our price cap in mind (even sponsored items count towards the price cap).

**Comment by garethellis0** [comment] 2019-02-03 01:40
This looks good to me! I think [rosserial](http://wiki.ros.org/rosserial_embeddedlinux) is a great option, sounds like people have got it to run on the `WRT54GL` router.

**Comment by raadkhan** [comment] 2019-02-04 00:51
Alright nice! I'll look into `WRT54GL` and propose it to the rest of the team

**Comment by raadkhan** [comment] 2019-10-05 19:20
Resolved with NM-2450's wide operating range and simply communicating with multiple machines by design in ROS

**Closed by raadkhan** 2019-10-05 19:20 UTC
